version: "3.8"

services:
  db:
    image: postgres:10.16-alpine
    container_name: "db-django-school"
    environment:
      - POSTGRES_DB=school-django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "7432:5432"
  redis:
    image: redis:6.2.1-alpine
    container_name: "cache-db-school"
    ports:
      - "6379:6379"
