# Generated by Django 3.1.7 on 2021-04-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_celphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='perfil_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
